risky: true

preset: symfony

enabled:
  - align_double_arrow
  - concat_with_spaces
  - ordered_use
  - strict

disabled:
  - concat_without_spaces
  - method_argument_space
  - native_constant_invocation_symfony
  - native_function_invocation_symfony
  - no_superfluous_phpdoc_tags_symfony
  - pow_to_exponentiation
  - pre_increment
  - unalign_double_arrow
  - unalign_equals
  - yoda_style

finder:
  name:
    - "*.php"
    - "build-manual"
    - "build-phar"
