language: php
os: linux
dist: trusty

jobs:
  include:
    - php: hhvm-3.18

  allow_failures:
    - php: hhvm-3.18
  fast_finish: true

install:
  - travis_retry composer update --no-interaction
  - travis_retry composer bin phpunit update --no-interaction --no-progress

script:
  - make test
