language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
  - COMPOSER_FLAGS=

before_install:
  - phpenv config-rm xdebug.ini

install:
  - travis_retry composer update --no-interaction --prefer-source $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
