language: php
os: linux
dist: bionic

jobs:
    include:
        - php: 5.5.9
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
          dist: trusty
        - php: 5.5
          dist: trusty
        - php: 5.6
          dist: xenial
        - php: 7.0
          dist: xenial
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: 7.4
        - php: nightly
          env: 'COMPOSER_FLAGS="--ignore-platform-reqs"'
        - php: hhvm-3.18
          dist: trusty
    allow_failures:
        - php: 5.5.9
          env: 'COMPOSER_FLAGS="--prefer-lowest --prefer-stable"'
        - php: nightly
          env: 'COMPOSER_FLAGS="--ignore-platform-reqs"'
    fast_finish: true

install:
    - travis_retry composer update --no-interaction $COMPOSER_FLAGS
    - |
      if [[ $TRAVIS_PHP_VERSION != 7.2* ]]; then
        composer bin phpunit update
      fi

script:
    - make test
    - |
      if [[ $TRAVIS_PHP_VERSION = 7.2* ]]; then
        make build -j 4
      fi

after_success:
    - bash <(curl -s https://codecov.io/bash)

before_deploy: make dist -j 4

deploy:
    provider: releases
    token:
        secure: LL8koDM1xDqzF9t0URHvmMPyWjojyd4PeZ7IW7XYgyvD6n1H6GYrVAeKCh5wfUKFbwHoa9s5AAn6pLzra00bODVkPTmUH+FSMWz9JKLw9ODAn8HvN7C+IooxmeClGHFZc0TfHfya8/D1E9C1iXtGGEoE/GqtaYq/z0C1DLpO0OU=
    file_glob: true
    file: dist/psysh-*.tar.gz
    skip_cleanup: true
    on:
        tags: true
        repo: bobthecow/psysh
        condition: $TRAVIS_PHP_VERSION = 7.2*
