language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - MIN_VERSIONS=true
  - MIN_VERSIONS=

before_install:
  - phpenv config-rm xdebug.ini

install:
  - travis_retry composer install --no-interaction --prefer-source
  - '[ "$MIN_VERSIONS" = true ] && composer update --no-interaction --prefer-source --prefer-lowest --prefer-stable'

script:
  - vendor/bin/phpunit
