name: Tests

on:
  push:
  pull_request:

jobs:
  php:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Set up problem matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Install PHPUnit
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer bin phpunit update --no-interaction --no-progress

      - name: Run tests
        run: make test

      - name: Upload coverage
        uses: codecov/codecov-action@v1

  build:
    name: Test Phar build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --no-interaction --no-progress

      - name: Build Phar binaries
        run: make build -j

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: build/*/psysh

      - name: Smoke test
        run: .github/bin/smoketest.sh

  php70-phar:
    name: PHP 7.0 Phar smoke test
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.0'
          tools: composer:v2
          coverage: none

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: build

      - name: Make binaries executable
        run: chmod +x build/*/psysh

      - name: Smoke test
        run: .github/bin/smoketest.sh psysh-php56 psysh-php56-compat
